networks:
  skyrim_net:
services:
  postgres:
    container_name: skyrim_db
    image:  postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - skyrim_net
    environment:
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
